version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  
  giveandtake-api:
    restart: always
    image: giveandtake-api
    build: 
      context: output/api
      dockerfile: Dockerfile
  
    container_name: giveandtake-api
    volumes:
      - "./output/api/app:/app"
    environment:
      - VIRTUAL_HOST=api.chovanhan.asia
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.chovanhan.asia
      - LETSENCRYPT_EMAIL=quyho@sioux.asia
    external_links:
      - mysql_shared_instance:mysql_local
  giveandtake-cms:
    restart: always
    image: pierrezemb/gostatic
    container_name: giveandtake-cms
    volumes:
      - "./output/cms:/srv/http"
      - "./volumes/nginx-cms/conf.d/:/etc/nginx/conf.d"
      - "./volumes/config/cms/config.js:/usr/share/nginx/html/config.js"
    ports:
      - '8043'
    environment:
      - VIRTUAL_HOST=cms.chovanhan.asia
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8043
      - LETSENCRYPT_HOST=cms.chovanhan.asia
      - LETSENCRYPT_EMAIL=quyho@sioux.asia

networks:
  default:
    external:
      name: webproxy